### ISSUE TITLE
Looking for package.json in node_modules?

### ISSUE THREAD

**Issue by beorn** [loopmode/electron-webpack-config#8]
Hi, I'm using `@loopmode/electron-webpack-config-yarn-workspaces` as follows:

```ts
const path = require('path')
const configureYarnWorkspaces = require("@loopmode/electron-webpack-config-yarn-workspaces")
const workspaceRoot = path.resolve(__dirname, "..")

module.exports = function (config) {
  return configureYarnWorkspaces(config, workspaceRoot)
}
```

which results in this error:
```console
$ yarn dev
yarn run v1.22.5
$ NLX_NPM_CLIENT=yarn electron-webpack dev
yarn.lock file detected :: using yarn as npm client for reinstalls
Using yarn for operations. You can override this by setting an env var of NLX_NPM_CLIENT as "npm" or "yarn".
Error: Cannot find module 'myproject/node_modules/package.json'
Require stack:
- myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/utils.js
- myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/configure.js
- myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/index.js
- myproject/app-el2/webpack.additions.js
- myproject/node_modules/electron-webpack/out/main.js
- myproject/node_modules/electron-webpack/out/dev/WebpackDevServerManager.js
- myproject/node_modules/electron-webpack/out/dev/dev-runner.js
- myproject/node_modules/electron-webpack/out/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/utils.js:18:22
    at Array.reduce (<anonymous>)
    at Object.createAliases (myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/utils.js:17:32)
    at configureYarnWorkspaces (myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/configure.js:16:29)
    at module.exports (myproject/app-el2/webpack.additions.js:33:10)
    at applyCustom (myproject/node_modules/electron-webpack/src/main.ts:257:16)
    at WebpackConfigurator.applyCustomModifications (myproject/node_modules/electron-webpack/src/main.ts:271:14)
    at WebpackConfigurator.configure (myproject/node_modules/electron-webpack/src/main.ts:246:54)
    at configure (myproject/node_modules/electron-webpack/src/main.ts:376:10)
    at DevRunner.startMainCompilation (myproject/node_modules/electron-webpack/src/dev/dev-runner.ts:71:24)
    at async Promise.all (index 2)
    at DevRunner.start (myproject/node_modules/electron-webpack/src/dev/dev-runner.ts:47:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/utils.js',
    'myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/configure.js',
    'myproject/node_modules/@loopmode/electron-webpack-config-yarn-workspaces/index.js',
    'myproject/app-el2/webpack.additions.js',
    'myproject/node_modules/electron-webpack/out/main.js',
    'myproject/node_modules/electron-webpack/out/dev/WebpackDevServerManager.js',
    'myproject/node_modules/electron-webpack/out/dev/dev-runner.js',
    'myproject/node_modules/electron-webpack/out/cli.js'
  ]
}
```

I've also tried with `tsconfig-paths-webpack-plugin` enabled, but with the same result.

The workspacePackages ends up being:
```js
  const workspacePackages = [
    'myproject/app-demo',
    'myproject/app-el',
   ... 
    'myproject/node_modules',
    'myproject/packages',
    'myproject/packages/app-main',
    ...
  ]
```

based on this config in `myproject/package.json`:
```json
  "workspaces": [
    "app-*",
    "packages/*"
  ],
```

**Comment by loopmode** [comment]
Hi @beorn 
That's weird, will have a look..

By the way there's not much magic involved in this package, especially if you only have a couple of workspace packages. All it does, or tried to do, is to set up a webpack alias for each found workspace package. You can easily manage it by hand.

Of course the idea was to make that work automatically 🙂

**Comment by loopmode** [comment]
Actually, looking at plugins.js, there are some additional caveats I tried to take care of, mind those if doing the aliases manually.

**Comment by beorn** [comment]
I currently just remove the WatchFilterPlugin entirely:
```js
  config.plugins = config.plugins.filter(
    plugin => plugin.constructor.name !== 'WatchFilterPlugin'
  )
```
but it does seem to result in some extraneous re-compilations.

... as it turns out I ended up not having the different packages compiled separately, but instead using `tsconfig.json:paths` to import their source directly in the main electron-webpack compile.  I guess what I really ended up needing is some version of this that looks at `tsconfig.json` instead of yarn workspaces :)

**Comment by loopmode** [comment]
Interesting find. By the way there is a somewhat related issue at electron-webpack. It's not about workspaces, but about making webpack automatically create aliases based on tsconfig paths: https://github.com/electron-userland/electron-webpack/issues/410
It mentions a plugin that might be useful for you

**Comment by beorn** [comment]
@loopmode Yes, I was the one that added that issue too... :)
